In [6]:
import numpy as np

A = np.array([[2, 3], [1, 4]])

determinant = np.linalg.det(A)
print("Determinant:", determinant)

inverse = np.linalg.inv(A)
print("Inverse:\n", inverse)

Determinant: 5.000000000000001
Inverse:
 [[ 0.8 -0.6]
 [-0.2  0.4]]


In [7]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [1. 5.]
Eigenvectors:
 [[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]


In [ ]:
U, S, Vt = np.linalg.svd(A)
print("U:\n", U)
print("Singular Values:", S)
print("V Transpose:\n", Vt)

U:
 [[-0.65520174 -0.75545395]
 [-0.75545395  0.65520174]]
Singular Values: [5.39834564 0.92620968]
V Transpose:
 [[-0.38268343 -0.92387953]
 [-0.92387953  0.38268343]]


In [11]:
# Reconstructing the original matrix from SVD components
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)
A_reconstructed = U @ Sigma @ Vt
print("Reconstructed A:\n", A_reconstructed)

Reconstructed A:
 [[2. 3.]
 [1. 4.]]
