In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix addition
C = A + B
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A + B:\n", C)

# Matrix Subtraction
D = A - B
print("A - B:\n", D)

# Matrix Multiplication
E = np.dot(A, B)
print("A * B:\n", E)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
A * B:
 [[19 22]
 [43 50]]


In [2]:
# Identity Matrix
I = np.eye(4)
print("Identity Matrix:\n", I)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Zero Matrix
Z = np.zeros((3, 3))
print("Zero Matrix:\n", Z)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Diagonal Matrix
D = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", D)

Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
# Matrix - Vector Multiplication
v = np.array([1, 2])
result = np.dot(A, v)
print("Matrix A:\n", A)
print("Vector v:\n", v)
print("A * v:\n", result)   

Matrix A:
 [[1 2]
 [3 4]]
Vector v:
 [1 2]
A * v:
 [ 5 11]
